<template>
    <content-grid>
        <feed-block-media></feed-block-media>
        <feed-block-media></feed-block-media>
        <feed-block-media></feed-block-media>
        <feed-block-media></feed-block-media>
        <feed-block-media></feed-block-media>
        <feed-block-media></feed-block-media>
    </content-grid>
</template>