<template>
    <post-grid>
        <feed-block-music></feed-block-music>
        <feed-block-music></feed-block-music>
        <feed-block-music></feed-block-music>
        <feed-block-music></feed-block-music>
        <feed-block-music></feed-block-music>
        <feed-block-music></feed-block-music>
        <feed-block-music></feed-block-music>
        <feed-block-music></feed-block-music>
        <feed-block-music></feed-block-music>
    </post-grid>
</template>